In [2]:
##Assignment 2
import numpy as np

In [3]:
#Q 1

x=np.arange(10)
x


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
x.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [10]:
##Q 2

x=np.arange(10).reshape(2,5)
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [11]:
y=np.ones(10).reshape(2,5)
y

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
np.concatenate((x,y))  ##for joining two arrays into one

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
##Q 3

np.hstack((x,y))   ##for joining each row of both arrays

array([[0., 1., 2., 3., 4., 1., 1., 1., 1., 1.],
       [5., 6., 7., 8., 9., 1., 1., 1., 1., 1.]])

In [15]:
##Q 4

x.reshape(10)  ##rehaped back to one array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
##Q 5

x=np.arange(15).reshape(5,3)
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [18]:
x.reshape(15)   ##converted to 1D

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [22]:
##Q 6 

y=x.reshape(15)
y.reshape(3,5)


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [29]:
##Q 7

x=np.arange(25).reshape(5,5)
np.square(x)   ##gives square of array

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]])

In [30]:
##Q 8

x=np.arange(30).reshape(5,6)
x

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [31]:
np.mean(x)

14.5

In [33]:
## Q 9

np.std(x)    ##gives standard deviation

8.65544144839919

In [34]:
##Q 10

np.median(x)   ##gives median of array

14.5

In [35]:
##Q 11

np.transpose(x)   ##gives transpose of array

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

In [40]:
## Q 12

x=np.arange(16).reshape(4,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [41]:
np.trace(x)  ##gives sum of diagonal values

30

In [44]:
## Q 13

np.linalg.det(x)  ##gives determinant of array

-2.9582283945787796e-30

In [47]:
##Q 14

np.percentile(x,5)  ##gives 5th percentile

0.75

In [48]:
np.percentile(x,95)  ##gives 95th percentile

14.25

In [51]:
##Q 15

np.isnan(x)  ##checking if array has null values

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])